# -*- coding: utf-8 -*-
"""loanpaybackPredictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sBhbHND7262al97nNJAYfk9SuavKmsHi
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score

dfTrain = pd.read_csv("/content/sample_data/train.csv")
dfTest = pd.read_csv("/content/sample_data/test.csv")

dfTrain.info()

dfTrain.describe()

dfTrain.columns

X = dfTrain.drop(columns = ["loan_paid_back"])
y = dfTrain["loan_paid_back"]

dfTrain['loan_paid_back'].value_counts()

X_train, X_valid, y_train, y_valid = train_test_split(X,y, test_size=0.2, stratify=y, random_state = 42)

float_features = ["annual_income", "debt_to_income_ratio","credit_score","loan_amount", "interest_rate"]

categorical_features = ['gender','marital_status','education_level','employment_status','loan_purpose','grade_subgrade']

featurePreprocessing = ColumnTransformer(transformers =[("num", StandardScaler(), float_features), ("cat", OneHotEncoder(drop="first", handle_unknown = "ignore"), categorical_features)])

log = LogisticRegression(max_iter=1000, solver="lbfgs")

clf = Pipeline(steps=[("preprocess", featurePreprocessing), ("model", log)])

clf.fit(X_train, y_train)

y_prob = clf.predict_proba(X_valid)[:,1]

accuracy = roc_auc_score(y_valid, y_prob)
print(accuracy)

clf.fit(X, y)

test_prob = clf.predict_proba(dfTest)[:,1]

id = "id"
loanpaid = "loan_paid_back"

sub = pd.DataFrame({id: dfTest[id], loanpaid: test_prob.round(1)})

sub.to_csv("submission.csv", index=False)